### ISSUE TITLE
Duplicated TriplesMap name in RML-star mappings (syntax-3)

### ISSUE THREAD

**Issue by anaigmo** [jhculb/Coding_Challenge#13]
Hi! 

I've reviewed the RML-star mappings (requested by @dachafra), and I found a minor error in [syntax-3.ttl](https://github.com/jhculb/Coding_Challenge/blob/main/src/rml-star-mappings/syntax-3.ttl): There are two TriplesMaps named the same: ':secondTM'. 

As far as I can see, the rest of the RML-star mappings are fine :)

**Comment by jhculb** [comment]
Hi @anaigmo,

Thank you very much for the review!

I'm merging the changes now.
