### ISSUE TITLE
Problems with the namespaces

### ISSUE THREAD

**Issue by dachafra** [jhculb/Coding_Challenge#16]
I've seen several problems with namespaces that are not correct.

For example:
https://github.com/jhculb/Coding_Challenge/blob/main/src/generated-rml-reified/syntax-1.ttl#L24 should be RML, not R2RML
https://github.com/jhculb/Coding_Challenge/blob/main/src/generated-rml-reified/syntax-1.ttl#L31 predicate should be R2RML and subject should be RDF.

Please review all of them

**Comment by jhculb** [comment]
Good morning, I'm currently working but should be able to pick this up at about 2-3pm CET :)
