### ISSUE TITLE
RML-Star Mappings

### ISSUE THREAD

**Issue by jhculb** [jhculb/Coding_Challenge#4]

**Comment by jhculb** [comment]
Hi @dachafra I think this is now ready for a full review

**Comment by jhculb** [comment]
Hi @dachafra I believe I have addressed the issues with NonAssertedTriplesMaps

**Comment by dachafra** [comment]
can I make a full review again?

**Comment by jhculb** [comment]
> can I make a full review again?

Yep (apologies, I forgot reactions don't notify)
