### ISSUE TITLE
Translation Mechanism

### ISSUE THREAD

**Issue by jhculb** [jhculb/Coding_Challenge#6]

**Comment by jhculb** [comment]
Hi @andimou @dachafra, it looks like merging issue 5 also merged issue 4. Seeing as 6 is dependent on accurate RML-Star (issue 4), and that issue 4 seemed close to correct, I will not be spending the time to restore issue 4 and branch 4-, and could the review on issue 4 be done on this branch please?

**Comment by dachafra** [comment]
sure, dont' worry

**Comment by jhculb** [comment]
Hi @dachafra @andimou, I've been mulling over the algorithm for producing a reification that matches my examples (or at least is valid) as it hasn't been clear how this would be done. 

Would an accurate algorithm be:

1. For triples (x) which have type (triplesMap or NonAssertedTriplesMap) in input graph:
   1. Create TriplesMap (X) in output graph
   2. Create subjectMap of a blank node
   2. Copy logical source from (x) to (X)
   3. Add predicateObjectMap to (X) with predicate rdf:type and object rdf:Statement
   4. Copy subjectMap (s) from (x) to (X)
      1. If (s) is of type quotedTriplesMap change this to ParentTriplesMap
   5. Split predicateObjectMap in (x) to two predicateObjectMaps in (X)
      1. The first is of type rdf:predicate and has constant object p [or the appropriate predicate title from (x)]
      2. The second is of type rdf:object and has object of the object in (x)

There is something to add to this about combining asserted triplesmaps I think, but this doesn't seem consistent among the reified RML, and also feels like something that could be added along the way / as an adjustment to the algorithm if it is sound. 
For example in reified RML bnode there's a single triplesmap with all of the information in it, [which I initially thought was due to the outer TriplesMap having constant information] but the nested-1 reified RML has two TriplesMaps, one with combined information of the two outer triplesmaps (c5 and c7) and one with the subject triplesmap (c1 and c3). 
[This also felt initially like it could be a nuance of NonAssertedTriplesMaps, but all TriplesMaps in nested-1.ttl RML-Star are TriplesMaps not NonAsserted.]

So I think the algorithm in it's current form probably outputs correctly reified RML, but not necessarily the most concise reification.

I am currently aiming to use RDFlib, which hasn't the easiest datamodels to work with, and my initial idea of doing something recursive was an inappropraite one, thankfully no more than a half hour went into that sketch, the rest of today has been spent playing around with RDFLib and also has been a little on-and-off as I've been dealing with family matters.
